version: '3.7'

services:
  frontend:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "127.0.0.1:3000:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000
    command: