version: "3.8"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/main
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    stdin_open: true
    